version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: production
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start:prod
    env_file:
      - .env.production
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata: