export const GOOGLE_STORAGE_CLIENT_ID = 'GOOGLE_STORAGE_CLIENT_ID';
export const GOOGLE_STORAGE_CLIENT_SECRET = 'BUGSNAG_ACCOUNT_API_KEY';
export const GOOGLE_STORAGE_MEDIA_BUCKET = 'GOOGLE_STORAGE_MEDIA_BUCKET';
export const BUGSNAG_ACCOUNT_API_KEY = 'BUGSNAG_ACCOUNT_API_KEY';
