export const JWT_CONSTANTS = {
  USER_LEVEL_PERMISSION: 'USER_LEVEL_PERMISSION',
  PASSWORD_RESET: 'PASSWORD_RESET_PERMISSION',
  JWT_SECRET: 'JWT_SECRET',
  PUBLIC_KEY: 'PUBLIC_KEY',
  PRIVATE_KEY: 'PRIVATE_KEY',
  PUBLIC_FULLKEY: `JWT_SECRET.PUBLIC_KEY`,
  PRIVATE_FULLKEY: 'JWT_SECRET.PRIVATE_KEY',
};
